### ISSUE TITLE
python-pip instead of pip in documentation

### ISSUE THREAD

**Issue by jaylenw** [stacksync/swift-API#1]
On the website here http://stacksync.org/storage-back-end for instructions setting up StackSync swift-API, picture below the instructions says,

```
sudo apt-get install pip
```

in GNU/Linux systems, pip is named python-pip, so it should be

```
sudo apt-get install python-pip
```

![screenshot from 2015-01-25 22 54 39](https://cloud.githubusercontent.com/assets/6505395/5896169/2c17ed86-a4e5-11e4-8ac8-67430096eb22.png)

In Ubuntu, here is the python-pip package

![screenshot from 2015-01-25 22 58 12](https://cloud.githubusercontent.com/assets/6505395/5896196/b7dc9c86-a4e5-11e4-944b-791c2a1b1745.png)

**Comment by Cotes** [comment]
Hi jaylenw,

Thank you very much. It is already fixed now! :)

**Comment by jaylenw** [comment]
Glad to help!
